---
- name: Configure Network Services
  hosts: utility
  gather_facts: true
  vars_files:
  - default_vars.yaml

  tasks:
  - name: Update /etc/ethers file
    template:
      src: templates/ethers.j2
      dest: /etc/ethers

  - name: Update /etc/hosts file
    template:
      src: templates/hosts.j2
      dest: /etc/hosts

  - name: Configure Dnsmasq
    template:
      src: templates/dnsmasq.conf.j2
      dest: /etc/dnsmasq.conf

  - name: Configure HAProxy
    include_tasks: configure_haproxy.yaml

  - name : Restart dnsmasq
    service:
      name: dnsmasq
      state: restarted

  - name : restart haproxy
    service:
      name: haproxy
      state: restarted
