- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    install_config: "{{ lookup('file', install_config_file) | from_yaml }}"
    cluster_name: "{{ install_config.metadata.name }}"
    worker_ign_file: "{{ cluster_name }}/worker.ign"
  tasks:
    - set_fact:
        worker_ip_addresses: "{{ worker_ips.split(',') }}"

    - name: Create a VM folder on vCenter for new OpenShift cluster
      vcenter_folder:
        hostname: "{{ install_config.platform.vsphere.vcenter }}"
        username: "{{ install_config.platform.vsphere.username }}"
        password: "{{ install_config.platform.vsphere.password }}"
        validate_certs: no
        datacenter: "{{install_config.platform.vsphere.datacenter}}"
        folder_name: "{{ cluster_name }}"
        folder_type: vm
        state: present

    - name: Set node role to compute
      set_fact:
        node_role: compute
        ignition_template: node.ign

    - name: Read worker ignition config
      set_fact:
        ignition_data: "{{ lookup('file', worker_ign_file) }}"

    - name: Create compute VMs
      include_tasks: nodes.yaml
      with_items: "{{ worker_ip_addresses }}"
      loop_control:
        loop_var: ip
        index_var: idx